import { db } from "../lib/db";
import { releaseTemplates } from "./schema";

// AUTO-GENERATED from the air-closet esa release-procedure doc (#3205).
// Trilingual (JA/EN/VI) master templates. Idempotent seed: `name` is unique,
// so re-running only inserts templates that don't exist yet.

type Seed = {
  category: string;
  name: string;
  repo: string;
  bodyJa: string;
  bodyEn: string;
  bodyVi: string;
};

const templates: Seed[] = [
  {
    "category": "Header",
    "name": "Header",
    "repo": "",
    "bodyJa": "以下の文言は**必ずリリース手順書の先頭に記載してください**。\nPR は **実際にリリース対象となるリポジトリ名・PR リンク** に修正してください。\n\n**リリースする PR は以下の通り**\n\n- air-closet-api：https://github.com/air-closet/air-closet-api/pull/2527\n\n### 以下の手順でリリースを行う",
    "bodyEn": "**Always include the following section at the beginning of the release procedure.**\nUpdate the repository name and PR link to match the actual release target.\n\n**PRs to be released**\n\n- air-closet-api: https://github.com/air-closet/air-closet-api/pull/2527\n\n### The release will be performed according to the procedure below",
    "bodyVi": "**Luôn đặt phần nội dung sau ở đầu ticket release procedure.**\nHãy chỉnh sửa tên repository và link PR cho đúng với nội dung release thực tế.\n\n**Những PR cần release**\n\n- air-closet-api: https://github.com/air-closet/air-closet-api/pull/2527\n\n### Quy trình release được thực hiện theo các bước dưới đây"
  },
  {
    "category": "Common",
    "name": "Merge PR to master",
    "repo": "",
    "bodyJa": "1. **以下の PR をマージする**\n\n   - [ ] リポジトリ名\n         https://github.com/air-closet/REPO_NAME/pull/??\n         ※ PR 番号を入力",
    "bodyEn": "1. **Merge the following PR**\n\n   - [ ] Repository name\n         https://github.com/air-closet/REPO_NAME/pull/??\n         ※ Enter PR number",
    "bodyVi": "1. **Merge PR sau**\n\n   - [ ] Tên repository\n         https://github.com/air-closet/REPO_NAME/pull/??\n         ※ Điền số PR"
  },
  {
    "category": "Common",
    "name": "Update submodule (ac-config/ac-migration)",
    "repo": "",
    "bodyJa": "※ レポジトリ名を更新（config/migration）\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-config\n         https://github.com/air-closet/air-closet-config/pull/??\n         ※ PR 番号を入力\n\n2. **以下のレポジトリで下記のコマンドを実行する**\n\n   `<リリース対象のブランチ>` はコロンの後のブランチ名に置き換える\n\n   - [ ] air-closet-api: `feature/AIRCLOSET-XXXXX`\n         ※ submodule を更新する必要があるブランチ名を入力\n\n   ```bash\n   TARGET_BRANCH=<リリース対象のブランチ>\n   PROJECT_NO=AIRCLOSET-XXXXX  # ※ プロジェクト番号を入力\n   TARGET_SUBMODULE=air-closet-config\n   git checkout $TARGET_BRANCH\n   git pull origin $TARGET_BRANCH\n   cd $TARGET_SUBMODULE\n   git checkout master\n   git pull origin master\n   cd ..\n   git add $TARGET_SUBMODULE\n   git commit -m \":wrench: $PROJECT_NO: update $TARGET_SUBMODULE\"\n   git push origin $TARGET_BRANCH\n   ```\n\n3. **サブモジュールの最新の SHA1 が取り込まれていることを確認する**\n\n   - [ ] air-closet-api\n         https://github.com/air-closet/air-closet-api/pull/??\n         ※ PR 番号を入力",
    "bodyEn": "※ Update repository name (config/migration)\n\n## air-closet release\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-config\n         https://github.com/air-closet/air-closet-config/pull/??\n         ※ Enter PR number\n\n2. **Execute the following commands in the target repository**\n\n   Replace `<target branch>` with the branch name after the colon\n\n   - [ ] air-closet-api: `feature/AIRCLOSET-XXXXX`\n         ※ Enter branch name that needs submodule update\n\n   ```bash\n   TARGET_BRANCH=<target branch>\n   PROJECT_NO=AIRCLOSET-XXXXX  # ※ Enter project number\n   TARGET_SUBMODULE=air-closet-config\n   git checkout $TARGET_BRANCH\n   git pull origin $TARGET_BRANCH\n   cd $TARGET_SUBMODULE\n   git checkout master\n   git pull origin master\n   cd ..\n   git add $TARGET_SUBMODULE\n   git commit -m \":wrench: $PROJECT_NO: update $TARGET_SUBMODULE\"\n   git push origin $TARGET_BRANCH\n   ```\n\n3. **Confirm the latest SHA1 of the submodule is included**\n\n   - [ ] air-closet-api\n         https://github.com/air-closet/air-closet-api/pull/??\n         ※ Enter PR number",
    "bodyVi": "※ Thay tên repository (config/migration)\n\n1. **Merge PR sau**\n\n   - [ ] air-closet-config\n         https://github.com/air-closet/air-closet-config/pull/??\n         ※ Điền số PR\n\n2. **Chạy các lệnh sau trong repository tương ứng**\n\n   Thay `<branch đích>` bằng tên branch sau dấu hai chấm\n\n   - [ ] air-closet-api: `feature/AIRCLOSET-XXXXX`\n         ※ Điền tên branch cần update submodule\n\n   ```bash\n   TARGET_BRANCH=<branch đích>\n   PROJECT_NO=AIRCLOSET-XXXXX  # ※ Điền số project\n   TARGET_SUBMODULE=air-closet-config\n   git checkout $TARGET_BRANCH\n   git pull origin $TARGET_BRANCH\n   cd $TARGET_SUBMODULE\n   git checkout master\n   git pull origin master\n   cd ..\n   git add $TARGET_SUBMODULE\n   git commit -m \":wrench: $PROJECT_NO: update $TARGET_SUBMODULE\"\n   git push origin $TARGET_BRANCH\n   ```\n\n3. **Xác nhận SHA1 mới nhất của submodule đã được đưa vào**\n\n   - [ ] air-closet-api\n         https://github.com/air-closet/air-closet-api/pull/??\n         ※ Điền số PR"
  },
  {
    "category": "Common",
    "name": "Execute SQL",
    "repo": "",
    "bodyJa": "1. **SQL の実行**\n\n   - [ ] 以下の SQL を実行する\n         Slack レビュースレッド: (リンクを貼る)\n         ```sql\n         -- 実行する SQL をここに記載\n         ```\n\n2. **SQL が実行されたことの確認**\n\n   - [ ] 以下の SQL を実行して正しくデータが書き換えられていることを確認する\n         ```sql\n         -- 確認用 SQL をここに記載\n         ```",
    "bodyEn": "1. **Execute SQL**\n\n   - [ ] Execute the following SQL\n         Slack review thread: (paste link)\n         ```sql\n         -- Enter SQL to execute here\n         ```\n\n2. **Confirm SQL execution**\n\n   - [ ] Execute the following SQL to confirm data was updated correctly\n         ```sql\n         -- Enter confirmation SQL here\n         ```",
    "bodyVi": "1. **Chạy SQL**\n\n   - [ ] Chạy SQL sau\n         Link thread Slack review SQL: (dán link)\n         ```sql\n         -- Điền SQL cần chạy ở đây\n         ```\n\n2. **Xác nhận đã chạy SQL**\n\n   - [ ] Chạy SQL sau để xác nhận data đã được cập nhật đúng\n         ```sql\n         -- Điền SQL dùng để confirm kết quả ở đây\n         ```"
  },
  {
    "category": "Common",
    "name": "Stop Auto-deletion of Unused Instances",
    "repo": "",
    "bodyJa": "1. **使われていないインスタンスを削除するスケジューラーを停止する**\n\n   - [ ] 以下の EventBridge を無効化する\n         https://ap-northeast-1.console.aws.amazon.com/events/home?region=ap-northeast-1#/eventbus/default/rules/clean-not-used-ec2-instan-CleanNotUsedEc2InstanceF-\n\n---\n\n**〜 リリースの実作業 〜**\n\n---\n\n2. **使われていないインスタンスを削除するスケジューラーを再開する**\n\n   - [ ] 以下の EventBridge を有効化する\n         https://ap-northeast-1.console.aws.amazon.com/events/home?region=ap-northeast-1#/eventbus/default/rules/clean-not-used-ec2-instan-CleanNotUsedEc2InstanceF-",
    "bodyEn": "1. **Stop the scheduler that deletes unused instances**\n\n   - [ ] Disable the following EventBridge rule\n         https://ap-northeast-1.console.aws.amazon.com/events/home?region=ap-northeast-1#/eventbus/default/rules/clean-not-used-ec2-instan-CleanNotUsedEc2InstanceF-\n\n---\n\n**~ Perform release work ~**\n\n---\n\n2. **Resume the scheduler that deletes unused instances**\n\n   - [ ] Enable the following EventBridge rule\n         https://ap-northeast-1.console.aws.amazon.com/events/home?region=ap-northeast-1#/eventbus/default/rules/clean-not-used-ec2-instan-CleanNotUsedEc2InstanceF-",
    "bodyVi": "1. **Dừng scheduler xóa instance không sử dụng**\n\n   - [ ] Vô hiệu hóa EventBridge sau\n         https://ap-northeast-1.console.aws.amazon.com/events/home?region=ap-northeast-1#/eventbus/default/rules/clean-not-used-ec2-instan-CleanNotUsedEc2InstanceF-\n\n---\n\n**~ Thực hiện công việc release ~**\n\n---\n\n2. **Khởi động lại scheduler xóa instance không sử dụng**\n\n   - [ ] Kích hoạt EventBridge sau\n         https://ap-northeast-1.console.aws.amazon.com/events/home?region=ap-northeast-1#/eventbus/default/rules/clean-not-used-ec2-instan-CleanNotUsedEc2InstanceF-"
  },
  {
    "category": "Common",
    "name": "Check environment variables",
    "repo": "",
    "bodyJa": "- [ ] 環境変数（env）をProduction環境に反映後、正しく設定されていることを示す証跡（エビデンス）を取得し、reviewerのレビューを受けている",
    "bodyEn": "- [ ] After applying environment variables (env) to the Production environment, evidence confirming correct configuration has been obtained and reviewed by the reviewer",
    "bodyVi": "- [ ] Sau khi áp dụng biến môi trường (env) lên môi trường Production, đã thu thập bằng chứng (evidence) xác nhận cấu hình chính xác và đã được reviewer xem xét"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet",
    "repo": "air-closet",
    "bodyJa": "リリースフローについては、以下の README を参照してください。\n\n- 通常のアプリリリース手順  \n  https://github.com/air-closet/air-closet?tab=readme-ov-file#release:~:text=%E3%81%8B%E3%82%89tag%E5%88%87%E3%82%8B-,Release,-develop%20%2D%20feature%E3%81%A7\n\n- ホットフィクス、またはアプリアイコンの**リリーステストなし**リリース手順  \n  https://github.com/air-closet/air-closet?tab=readme-ov-file#release:~:text=master%E3%81%AB%E3%83%9E%E3%83%BC%E3%82%B8-,Release%3A,-Without%20Release%20Test\n\n### チェック項目\n\n- [ ] リリースブランチは `master` にマージされていますか？\n- [ ] リリースブランチは `develop` にマージされていますか？",
    "bodyEn": "Please refer to the README below for the release flow.\n\n- Normal app release procedure  \n  https://github.com/air-closet/air-closet?tab=readme-ov-file#release:~:text=%E3%81%8B%E3%82%89tag%E5%88%87%E3%82%8B-,Release,-develop%20%2D%20feature%E3%81%A7\n\n- Hotfix or **release without release test** (e.g. app icon change)  \n  https://github.com/air-closet/air-closet?tab=readme-ov-file#release:~:text=master%E3%81%AB%E3%83%9E%E3%83%BC%E3%82%B8-,Release%3A,-Without%20Release%20Test\n\n### Checklist\n\n- [ ] Has the release branch been merged into `master`?\n- [ ] Has the release branch been merged into `develop`?",
    "bodyVi": "Vui lòng tham khảo README dưới đây để nắm rõ quy trình release.\n\n- Quy trình release ứng dụng thông thường  \n  https://github.com/air-closet/air-closet?tab=readme-ov-file#release:~:text=%E3%81%8B%E3%82%89tag%E5%88%87%E3%82%8B-,Release,-develop%20%2D%20feature%E3%81%A7\n\n- Release hotfix hoặc release **không chạy release test** (ví dụ: đổi icon app)  \n  https://github.com/air-closet/air-closet?tab=readme-ov-file#release:~:text=master%E3%81%AB%E3%83%9E%E3%83%BC%E3%82%B8-,Release%3A,-Without%20Release%20Test\n\n### Checklist\n\n- [ ] Release branch đã được merge vào `master` chưa?\n- [ ] Release branch đã được merge vào `develop` chưa?"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-ssr",
    "repo": "air-closet-ssr",
    "bodyJa": "## air-closet-ssr をリリースする\n\n1. **サーバー増強されていないことを確認**\n\n   - [ ] Slack の `#release` を確認し、増強中でないことを確認する\n\n2. **以下の PR をマージする**\n\n   - [ ] air-closet-ssr  \n          https://github.com/air-closet/air-closet-ssr/pull/2825  \n          ※ PR リンクは必ず変更する\n\n3. **air-closet-infrastructure にリリース対象の SHA1 をセット**\n\n   - [ ] `air-closet-infrastructure/ansible/group_vars/ac-ssr-prod.yml` の\n          `release_sha1` を最新の `master` の SHA1 に更新する\n   - [ ] 以下を実行して commit / push する  \n          `PROJECT_NO=AIRCLOSET-XXXXX`（変更必須）  \n          `git commit -am \":rocket:$PROJECT_NO: release to prod\"`  \n          `git push origin master`\n\n4. **プレ本番環境（black）にリリース**\n\n   - [ ] 以下の手順に従って `ac-ssr-prod` をリリースする  \n          https://air-closet.esa.io/posts/1594\n   - [ ] 完了後、以下 URL にアクセスし、  \n          Network タブで `X-Ac-Api-Revision` が  \n          air-closet-ssr の `master` SHA1 と一致していることを確認  \n          https://prod-black.air-closet.com/status/\n\n5. **プレ本番環境での動作確認**  \n   ※ `ac-web-static2` に依存して確認できない場合はスキップ\n\n   - [ ] ログインできる\n     - [ ] 今回のアイテムが表示される\n     - [ ] 過去アイテムが表示される\n   - [ ] 無料会員登録ができる\n   - [ ] 月額会員登録ができる\n\n6. **本番環境にリリース**\n\n   - [ ] 同様の手順で `ac-ssr-prod` を本番環境にリリースする\n   - [ ] `X-Ac-Api-Revision` が `master` SHA1 と一致していることを確認  \n          https://www.air-closet.com/status\n\n7. **本番環境での動作確認**\n   - [ ] ログインできる\n   - [ ] アイテムが正しく表示される\n   - [ ] 会員登録ができる",
    "bodyEn": "## Release air-closet-ssr\n\n1. **Confirm no server scaling is in progress**\n\n   - [ ] Check Slack `#release` and confirm no scaling is running\n\n2. **Merge the following PR**\n\n   - [ ] air-closet-ssr  \n          https://github.com/air-closet/air-closet-ssr/pull/2825  \n          Update the PR link as needed\n\n3. **Set the release SHA1 in air-closet-infrastructure**\n\n   - [ ] Update `release_sha1` in  \n          `air-closet-infrastructure/ansible/group_vars/ac-ssr-prod.yml`  \n          to the latest `master` SHA1\n   - [ ] Commit and push with the appropriate project number\n\n4. **Release to pre-production (black)**\n\n   - [ ] Release `ac-ssr-prod` following the procedure below  \n          https://air-closet.esa.io/posts/1594\n   - [ ] After completion, confirm `X-Ac-Api-Revision` matches `master` SHA1  \n          https://prod-black.air-closet.com/status/\n\n5. **Verify behavior in pre-production**  \n   Skip if blocked by dependency on `ac-web-static2`\n\n   - [ ] Login works\n   - [ ] Item list displays correctly\n   - [ ] Free membership registration works\n   - [ ] Monthly membership registration works\n\n6. **Release to production**\n\n   - [ ] Release `ac-ssr-prod` to production using the same procedure\n   - [ ] Confirm revision header  \n          https://www.air-closet.com/status\n\n7. **Verify behavior in production**\n   - [ ] Login works\n   - [ ] Item list displays correctly\n   - [ ] Membership registration works",
    "bodyVi": "## Release air-closet-ssr\n\n1. **Xác nhận không có quá trình mở rộng server**\n\n   - [ ] Kiểm tra Slack `#release` và xác nhận không có scaling đang chạy\n\n2. **Merge PR dưới đây**\n\n   - [ ] air-closet-ssr  \n          https://github.com/air-closet/air-closet-ssr/pull/2825  \n          Cần thay đổi link PR cho đúng\n\n3. **Cập nhật SHA1 release trong air-closet-infrastructure**\n\n   - [ ] Cập nhật `release_sha1` trong  \n          `air-closet-infrastructure/ansible/group_vars/ac-ssr-prod.yml`  \n          thành SHA1 mới nhất của `master`\n   - [ ] Commit và push với mã project phù hợp\n\n4. **Release lên môi trường pre-production (black)**\n\n   - [ ] Thực hiện release `ac-ssr-prod` theo hướng dẫn sau  \n          https://air-closet.esa.io/posts/1594\n   - [ ] Sau khi hoàn tất, truy cập URL bên dưới và kiểm tra  \n          `X-Ac-Api-Revision` trùng với SHA1 của `master`  \n          https://prod-black.air-closet.com/status/\n\n5. **Kiểm tra trên môi trường pre-production**  \n   Bỏ qua nếu bị phụ thuộc vào `ac-web-static2`\n\n   - [ ] Đăng nhập được\n   - [ ] Hiển thị đúng item (hiện tại / trước đây)\n   - [ ] Đăng ký thành viên miễn phí được\n   - [ ] Đăng ký thành viên trả phí được\n\n6. **Release lên môi trường production**\n\n   - [ ] Release `ac-ssr-prod` lên production theo cùng quy trình\n   - [ ] Kiểm tra revision  \n          https://www.air-closet.com/status\n\n7. **Kiểm tra trên môi trường production**\n   - [ ] Đăng nhập được\n   - [ ] Hiển thị item chính xác\n   - [ ] Đăng ký thành viên hoạt động bình thường"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-api",
    "repo": "air-closet-api",
    "bodyJa": "## air-closet-api をリリースする\n\n1. **サーバー増強されていないことを確認**\n\n   - [ ] Slack の `#release` を確認し、増強中でないことを確認する\n\n2. **以下の PR をマージする**\n\n   - [ ] air-closet-api  \n          https://github.com/air-closet/air-closet-api/pull/2529  \n          ※ PR リンクは必ず変更する\n\n3. **air-closet-infrastructure にリリース対象の SHA1 をセット**\n\n   - [ ] `air-closet-infrastructure/ansible/group_vars/ac-api-prod.yml` の  \n          `release_sha1` を最新の `master` の SHA1 に更新する\n   - [ ] PROJECT_NO を指定して commit / push する  \n          例: `:rocket:AIRCLOSET-XXXXX: release to prod`（変更必須）\n\n4. **プレ本番環境（black）にリリース**\n\n   - [ ] 以下の手順に従って `ac-api-prod` をリリースする  \n          https://air-closet.esa.io/posts/1594\n   - [ ] 完了後、以下 URL にアクセスし、  \n          Network タブで `X-Ac-Api-Revision` が  \n          air-closet-api の `master` SHA1 と一致していることを確認  \n          https://api-black.air-closet.com/status/\n\n5. **プレ本番環境での動作確認**\n\n   - [ ] ログインできる\n     - [ ] 今回のアイテムが表示される\n     - [ ] 過去アイテムが表示される\n   - [ ] 無料会員登録ができる\n   - [ ] 月額会員登録ができる\n\n6. **本番環境にリリース**\n\n   - [ ] 同様の手順で `ac-api-prod` を本番環境にリリースする\n   - [ ] `X-Ac-Api-Revision` が `master` SHA1 と一致していることを確認  \n          https://api.air-closet.com/status\n\n7. **本番環境での動作確認**\n   - [ ] ログインできる\n   - [ ] アイテムが正しく表示される\n   - [ ] 会員登録ができる",
    "bodyEn": "## Release air-closet-api\n\n1. **Confirm no server scaling is in progress**\n\n   - [ ] Check Slack `#release` and confirm no scaling is running\n\n2. **Merge the following PR**\n\n   - [ ] air-closet-api  \n          https://github.com/air-closet/air-closet-api/pull/2529  \n          Update the PR link as needed\n\n3. **Set the release SHA1 in air-closet-infrastructure**\n\n   - [ ] Update `release_sha1` in  \n          `air-closet-infrastructure/ansible/group_vars/ac-api-prod.yml`  \n          to the latest `master` SHA1\n   - [ ] Commit and push with the correct project number  \n          Example commit message includes `AIRCLOSET-XXXXX`\n\n4. **Release to pre-production (black)**\n\n   - [ ] Release `ac-api-prod` following the procedure below  \n          https://air-closet.esa.io/posts/1594\n   - [ ] Confirm `X-Ac-Api-Revision` matches the `master` SHA1  \n          https://api-black.air-closet.com/status/\n\n5. **Verify behavior in pre-production**\n\n   - [ ] Login works\n   - [ ] Current and past items are displayed\n   - [ ] Free membership registration works\n   - [ ] Monthly membership registration works\n\n6. **Release to production**\n\n   - [ ] Release `ac-api-prod` to production using the same procedure\n   - [ ] Confirm revision header  \n          https://api.air-closet.com/status\n\n7. **Verify behavior in production**\n   - [ ] Login works\n   - [ ] Items display correctly\n   - [ ] Membership registration works",
    "bodyVi": "## Release air-closet-api\n\n1. **Xác nhận không có quá trình mở rộng server**\n\n   - [ ] Kiểm tra Slack `#release` để đảm bảo không có scaling đang chạy\n\n2. **Merge PR bên dưới**\n\n   - [ ] air-closet-api  \n          https://github.com/air-closet/air-closet-api/pull/2529  \n          Cần thay đổi link PR cho đúng\n\n3. **Cập nhật SHA1 release trong air-closet-infrastructure**\n\n   - [ ] Cập nhật `release_sha1` trong  \n          `air-closet-infrastructure/ansible/group_vars/ac-api-prod.yml`  \n          thành SHA1 mới nhất của `master`\n   - [ ] Commit và push với mã project phù hợp (AIRCLOSET-XXXXX)\n\n4. **Release lên môi trường pre-production (black)**\n\n   - [ ] Thực hiện release `ac-api-prod` theo hướng dẫn  \n          https://air-closet.esa.io/posts/1594\n   - [ ] Kiểm tra `X-Ac-Api-Revision` trùng với SHA1 của `master`  \n          https://api-black.air-closet.com/status/\n\n5. **Kiểm tra trên môi trường pre-production**\n\n   - [ ] Đăng nhập được\n   - [ ] Hiển thị đúng item hiện tại và trước đây\n   - [ ] Đăng ký thành viên miễn phí được\n   - [ ] Đăng ký thành viên trả phí được\n\n6. **Release lên môi trường production**\n\n   - [ ] Release `ac-api-prod` lên production theo cùng quy trình\n   - [ ] Kiểm tra revision  \n          https://api.air-closet.com/status\n\n7. **Kiểm tra trên môi trường production**\n   - [ ] Đăng nhập được\n   - [ ] Hiển thị item chính xác\n   - [ ] Đăng ký thành viên hoạt động bình thường"
  },
  {
    "category": "airCloset",
    "name": "Release ac-web-static2",
    "repo": "ac-web-static2",
    "bodyJa": "## ac-web-static2 をリリースする\n\n1. **以下の PR をマージする**\n\n   - [ ] ac-web-static2  \n          https://github.com/air-closet/ac-web-static2/pull/XXX  \n          ※ PR リンクは必ず変更する\n\n2. **main ブランチの CI が成功していることを確認する**\n\n   - [ ] [GitHub Actions](https://github.com/air-closet/ac-web-static2/actions/workflows/ci.yml) で CI ビルドが成功していることを確認する\n\n3. **ステージングにデプロイする**\n\n   - [ ] `npm run deploy:stg` を実行する\n   - [ ] https://stg.air-closet.com で変更内容を確認する\n\n4. **本番にデプロイする**\n\n   - [ ] `npm run deploy:prod` を実行する\n\n5. **リリース完了の確認**\n   - [ ] https://www.air-closet.com で変更内容が正しく反映されていることを確認する",
    "bodyEn": "## Release ac-web-static2\n\n1. **Merge the following PR**\n\n   - [ ] ac-web-static2  \n          https://github.com/air-closet/ac-web-static2/pull/XXX  \n          Update the PR link as needed\n\n2. **Wait for CI to pass on main**\n\n   - [ ] Confirm CI build succeeded in [GitHub Actions](https://github.com/air-closet/ac-web-static2/actions/workflows/ci.yml)\n\n3. **Deploy to staging**\n\n   - [ ] Execute `npm run deploy:stg`\n   - [ ] Verify changes on https://stg.air-closet.com\n\n4. **Deploy to production**\n\n   - [ ] Execute `npm run deploy:prod`\n\n5. **Verify the release**\n   - [ ] Verify that the changes are correctly reflected on https://www.air-closet.com",
    "bodyVi": "## Release ac-web-static2\n\n1. **Merge PR sau**\n\n   - [ ] ac-web-static2  \n          https://github.com/air-closet/ac-web-static2/pull/XXX  \n          ※ Nhớ thay đổi link PR\n\n2. **Xác nhận CI trên branch main đã thành công**\n\n   - [ ] Xác nhận CI build đã thành công trên [GitHub Actions](https://github.com/air-closet/ac-web-static2/actions/workflows/ci.yml)\n\n3. **Deploy lên staging**\n\n   - [ ] Chạy `npm run deploy:stg`\n   - [ ] Xác nhận các thay đổi trên https://stg.air-closet.com\n\n4. **Deploy lên production**\n\n   - [ ] Chạy `npm run deploy:prod`\n\n5. **Xác nhận release hoàn tất**\n   - [ ] Xác nhận các thay đổi đã được phản ánh đúng trên https://www.air-closet.com"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-console",
    "repo": "air-closet-console",
    "bodyJa": "## air-closet-console のリリース\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-console  \n          https://github.com/air-closet/air-closet-console/pull/2838  \n          ※ PR リンクは必ず変更する\n\n2. **air-closet-infrastructure にリリース対象の SHA1 をセットする**\n\n   - [ ] `air-closet-infrastructure/ansible/group_vars/ac-console-app-prod.yml` の  \n          `release_sha1` を master ブランチ最新の SHA1 に更新する\n   - [ ] 変更をコミットし、master に push する  \n          （プロジェクト番号は案件に合わせて変更）\n\n3. **プレ本番環境にリリースする**\n\n   - [ ] 手順書に従って `ac-console-app-prod` をリリースする  \n          https://air-closet.esa.io/posts/1594\n   - [ ] リリース完了後、以下 URL にアクセスし  \n          Network タブで `X-Ac-Api-Revision` が  \n          air-closet-console の master SHA1 と一致していることを確認する  \n          https://console-black.air-closet.com/status\n\n4. **プレ本番環境での動作確認**\n\n   - [ ] ユーザー一覧にユーザーが表示される\n   - [ ] ユーザーカルテが正常に開ける\n\n5. **本番環境にリリースする**\n\n   - [ ] 手順書に従って `ac-console-app-prod` をリリースする  \n          https://air-closet.esa.io/posts/1594\n   - [ ] リリース完了後、以下 URL にアクセスし  \n          `X-Ac-Api-Revision` が master SHA1 と一致していることを確認する  \n          https://console.air-closet.com/status\n\n6. **本番環境での動作確認**\n   - [ ] ユーザー一覧にユーザーが表示される\n   - [ ] ユーザーカルテが正常に開ける",
    "bodyEn": "## Release air-closet-console\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-console  \n          https://github.com/air-closet/air-closet-console/pull/2838  \n          Update the PR link as needed\n\n2. **Set the release SHA1 in air-closet-infrastructure**\n\n   - [ ] Update `release_sha1` in  \n          `air-closet-infrastructure/ansible/group_vars/ac-console-app-prod.yml`  \n          to the latest SHA1 of the master branch\n   - [ ] Commit the change and push to master  \n          (adjust the project number as needed)\n\n3. **Release to pre-production**\n\n   - [ ] Release `ac-console-app-prod` following the procedure below  \n          https://air-closet.esa.io/posts/1594\n   - [ ] After completion, access the URL below and confirm that  \n          `X-Ac-Api-Revision` matches the master SHA1 of air-closet-console  \n          https://console-black.air-closet.com/status\n\n4. **Verify functionality in pre-production**\n\n   - [ ] Users are displayed in the user list\n   - [ ] User detail (user chart) can be opened correctly\n\n5. **Release to production**\n\n   - [ ] Release `ac-console-app-prod` following the procedure below  \n          https://air-closet.esa.io/posts/1594\n   - [ ] After completion, confirm that  \n          `X-Ac-Api-Revision` matches the master SHA1  \n          https://console.air-closet.com/status\n\n6. **Verify functionality in production**\n   - [ ] Users are displayed in the user list\n   - [ ] User detail (user chart) can be opened correctly",
    "bodyVi": "## Release air-closet-console\n\n1. **Merge PR bên dưới**\n\n   - [ ] air-closet-console  \n          https://github.com/air-closet/air-closet-console/pull/2838  \n          Cần thay đổi link PR cho đúng\n\n2. **Thiết lập SHA1 release trong air-closet-infrastructure**\n\n   - [ ] Cập nhật `release_sha1` trong  \n          `air-closet-infrastructure/ansible/group_vars/ac-console-app-prod.yml`  \n          thành SHA1 mới nhất của nhánh master\n   - [ ] Commit thay đổi và push lên master  \n          (điền mã project phù hợp)\n\n3. **Release lên môi trường pre-production**\n\n   - [ ] Thực hiện release `ac-console-app-prod` theo hướng dẫn  \n          https://air-closet.esa.io/posts/1594\n   - [ ] Sau khi hoàn tất, truy cập URL bên dưới và xác nhận  \n          `X-Ac-Api-Revision` trùng với SHA1 của master  \n          https://console-black.air-closet.com/status\n\n4. **Kiểm tra trên môi trường pre-production**\n\n   - [ ] Danh sách người dùng hiển thị bình thường\n   - [ ] Mở được trang chi tiết người dùng\n\n5. **Release lên môi trường production**\n\n   - [ ] Thực hiện release `ac-console-app-prod` theo hướng dẫn  \n          https://air-closet.esa.io/posts/1594\n   - [ ] Xác nhận `X-Ac-Api-Revision` trùng với SHA1 của master  \n          https://console.air-closet.com/status\n\n6. **Kiểm tra trên môi trường production**\n   - [ ] Danh sách người dùng hiển thị bình thường\n   - [ ] Mở được trang chi tiết người dùng"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-styling-console",
    "repo": "air-closet-styling-console",
    "bodyJa": "## air-closet-styling-console のリリース\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-styling-console  \n          https://github.com/air-closet/air-closet-styling-console/pull/593  \n          ※ PR リンクは必ず変更する\n\n2. **air-closet-console をプレ本番環境にリリースする**\n\n   - [ ] 手順書に従って `ac-console-app-prod` をリリースする  \n          https://air-closet.esa.io/posts/1594\n\n3. **air-closet-styling-console をプレ本番環境にリリースする**\n\n   - [ ] `npm run deploy:pre-prod` を実行する\n   - [ ] ブランチ名が master であることを確認する\n   - [ ] デプロイ対象のコミット SHA1 が master 最新であることを確認する\n   - [ ] デプロイ後、以下 URL にアクセスし、表示される SHA1 が  \n          リリース対象の SHA1 と一致していることを確認する  \n          https://console-black.air-closet.com/styling-console/release-version\n\n4. **プレ本番環境での動作確認**\n\n   - [ ] ユーザーカルテが表示される\n   - [ ] 選定送信ができる  \n          （テストユーザーで実行し、送信後は「選定前に戻す」ボタンで元に戻す）\n\n5. **air-closet-styling-console を本番環境にリリースする**\n\n   - [ ] `npm run deploy:prod` を実行する\n   - [ ] ブランチ名が master であることを確認する\n   - [ ] デプロイ対象のコミット SHA1 が master 最新であることを確認する\n   - [ ] デプロイ後、以下 URL にアクセスし、表示される SHA1 が  \n          リリース対象の SHA1 と一致していることを確認する  \n          https://console.air-closet.com/styling-console/release-version\n\n6. **本番環境での動作確認**\n   - [ ] ユーザーカルテが表示される\n   - [ ] 選定送信ができる  \n          （テストユーザーで実行し、送信後は「選定前に戻す」ボタンで元に戻す）",
    "bodyEn": "## Release air-closet-styling-console\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-styling-console\n          https://github.com/air-closet/air-closet-styling-console/pull/593  \n          Update the PR link as needed\n\n2. **Release air-closet-console to pre-production**\n\n   - [ ] Release `ac-console-app-prod` following the procedure below  \n          https://air-closet.esa.io/posts/1594\n\n3. **Release air-closet-styling-console to pre-production**\n\n   - [ ] Execute `npm run deploy:pre-prod`\n   - [ ] Confirm the branch name is master\n   - [ ] Confirm the deployed commit SHA1 is the latest master SHA1\n   - [ ] After deployment, access the URL below and confirm the SHA1 matches  \n          https://console-black.air-closet.com/styling-console/release-version\n\n4. **Verify functionality in pre-production**\n\n   - [ ] User detail page is displayed\n   - [ ] Styling submission can be sent  \n          (Use a test user and revert to pre-selection state afterward)\n\n5. **Release air-closet-styling-console to production**\n\n   - [ ] Execute `npm run deploy:prod`\n   - [ ] Confirm the branch name is master\n   - [ ] Confirm the deployed commit SHA1 is the latest master SHA1\n   - [ ] Verify the SHA1 at the following URL  \n          https://console.air-closet.com/styling-console/release-version\n\n6. **Verify functionality in production**\n   - [ ] User detail page is displayed\n   - [ ] Styling submission can be sent  \n          (Use a test user and revert to pre-selection state afterward)",
    "bodyVi": "## Release air-closet-styling-console\n\n1. **Merge PR bên dưới**\n\n   - [ ] air-closet-styling-console\n          https://github.com/air-closet/air-closet-styling-console/pull/593  \n          Cần thay đổi link PR cho đúng\n\n2. **Release air-closet-console lên môi trường pre-production**\n\n   - [ ] Release `ac-console-app-prod` theo hướng dẫn  \n          https://air-closet.esa.io/posts/1594\n\n3. **Release air-closet-styling-console lên pre-production**\n\n   - [ ] Chạy `npm run deploy:pre-prod`\n   - [ ] Xác nhận branch đang là master\n   - [ ] Xác nhận commit SHA1 deploy là SHA1 mới nhất của master\n   - [ ] Sau khi deploy, truy cập URL bên dưới và kiểm tra SHA1  \n          https://console-black.air-closet.com/styling-console/release-version\n\n4. **Kiểm tra trên môi trường pre-production**\n\n   - [ ] Hiển thị được user card\n   - [ ] Thực hiện được gửi chọn đồ  \n          (Dùng user test và hoàn tác về trạng thái trước khi chọn)\n\n5. **Release air-closet-styling-console lên production**\n\n   - [ ] Chạy `npm run deploy:prod`\n   - [ ] Xác nhận branch là master\n   - [ ] Xác nhận commit SHA1 deploy là SHA1 mới nhất của master\n   - [ ] Kiểm tra SHA1 tại URL bên dưới  \n          https://console.air-closet.com/styling-console/release-version\n\n6. **Kiểm tra trên môi trường production**\n   - [ ] Hiển thị được user card\n   - [ ] Thực hiện được gửi chọn đồ  \n          (Dùng user test và hoàn tác về trạng thái trước khi chọn)"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-styling-api",
    "repo": "air-closet-styling-api",
    "bodyJa": "## air-closet-styling-api のリリース\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-styling-api\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         ※ PR リンクは必ず変更する\n\n2. **air-closet-infrastructure にリリース対象の SHA1 をセットする**\n\n   - [ ] `air-closet-infrastructure/ansible/group_vars/ac-styling-console-api-prod.yml` の\n         `release_sha1` を最新の `master` の SHA1 に更新する\n   - [ ] 以下を実行する\n         `PROJECT_NO=AIRCLOSET-XXXXX`（変更必須）\n         `git commit -am \":rocket:$PROJECT_NO: release to prod\"`\n         `git push origin master`\n\n3. **プレ本番環境にリリースする**\n\n   - [ ] 以下の手順に従って `ac-styling-console-api-prod` をリリースする\n         https://air-closet.esa.io/posts/1594\n   - [ ] デプロイ後、以下 URL にアクセスし\n         `X-Ac-Api-Revision` が `master` の SHA1 と一致していることを確認する\n         https://styling-api-black.air-closet.com/status\n\n4. **プレ本番環境で動作確認を行う**\n\n   - [ ] ユーザーカルテが表示される\n   - [ ] 選定送信ができる\n         （テストユーザーで実行し、送信後は「選定前に戻す」こと）\n\n5. **本番環境にリリースする**\n\n   - [ ] 以下の手順に従って `ac-styling-console-api-prod` をリリースする\n         https://air-closet.esa.io/posts/1594\n   - [ ] `X-Ac-Api-Revision` が `master` の SHA1 と一致することを確認する\n         https://styling-api.air-closet.com/status\n\n6. **本番環境で動作確認を行う**\n   - [ ] ユーザーカルテが表示される\n   - [ ] 選定送信ができる",
    "bodyEn": "## Release air-closet-styling-api\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-styling-api\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         Update the PR link as needed\n\n2. **Set the release SHA1 in air-closet-infrastructure**\n\n   - [ ] Update `release_sha1` in\n         `air-closet-infrastructure/ansible/group_vars/ac-styling-console-api-prod.yml`\n         to the latest SHA1 of the `master` branch\n   - [ ] Execute the following\n         `PROJECT_NO=AIRCLOSET-XXXXX` (Required)\n         `git commit -am \":rocket:$PROJECT_NO: release to prod\"`\n         `git push origin master`\n\n3. **Release to pre-production**\n\n   - [ ] Release `ac-styling-console-api-prod` following the procedure below\n         https://air-closet.esa.io/posts/1594\n   - [ ] After deployment, confirm `X-Ac-Api-Revision` matches the `master` SHA1\n         https://styling-api-black.air-closet.com/status\n\n4. **Verify functionality in pre-production**\n\n   - [ ] User chart is displayed\n   - [ ] Styling submission works\n         (Use a test user and revert after submission)\n\n5. **Release to production**\n\n   - [ ] Release `ac-styling-console-api-prod` following the procedure below\n         https://air-closet.esa.io/posts/1594\n   - [ ] Confirm `X-Ac-Api-Revision` matches the `master` SHA1\n         https://styling-api.air-closet.com/status\n\n6. **Verify functionality in production**\n   - [ ] User chart is displayed\n   - [ ] Styling submission works",
    "bodyVi": "## Release air-closet-styling-api\n\n1. **Merge PR bên dưới**\n\n   - [ ] air-closet-styling-api\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         Cần thay đổi link PR cho đúng\n\n2. **Cập nhật SHA1 release trong air-closet-infrastructure**\n\n   - [ ] Cập nhật `release_sha1` trong\n         `air-closet-infrastructure/ansible/group_vars/ac-styling-console-api-prod.yml`\n         thành SHA1 mới nhất của nhánh `master`\n   - [ ] Thực hiện các lệnh sau\n         `PROJECT_NO=AIRCLOSET-XXXXX` (Bắt buộc)\n         `git commit -am \":rocket:$PROJECT_NO: release to prod\"`\n         `git push origin master`\n\n3. **Release lên môi trường pre-production**\n\n   - [ ] Release `ac-styling-console-api-prod` theo hướng dẫn sau\n         https://air-closet.esa.io/posts/1594\n   - [ ] Sau khi deploy, kiểm tra `X-Ac-Api-Revision` trùng với SHA1 của `master`\n         https://styling-api-black.air-closet.com/status\n\n4. **Kiểm tra chức năng trên môi trường pre-production**\n\n   - [ ] Hiển thị user chart\n   - [ ] Gửi chọn đồ thành công\n         (Dùng user test và hoàn tác sau khi gửi)\n\n5. **Release lên môi trường production**\n\n   - [ ] Release `ac-styling-console-api-prod` theo hướng dẫn sau\n         https://air-closet.esa.io/posts/1594\n   - [ ] Kiểm tra `X-Ac-Api-Revision` trùng với SHA1 của `master`\n         https://styling-api.air-closet.com/status\n\n6. **Kiểm tra chức năng trên môi trường production**\n   - [ ] Hiển thị user chart\n   - [ ] Gửi chọn đồ thành công"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-migration",
    "repo": "air-closet-migration",
    "bodyJa": "## air-closet-migration のリリース\n\n#### 📝 開発者記入欄\n\n| 項目                                     | 値       |\n| ---------------------------------------- | -------- |\n| STG 環境での実行時間                     | XX [秒]  |\n| 深夜リリースが必要か? (午前 2:30 - 5:30) | Yes / No |\n\n#### 手順\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-migration\n         https://github.com/air-closet/air-closet-ssr/pull/2825\n         ※ PR リンクは必ず変更する\n\n2. **submodule の更新（必要な場合）**\n\n   - [ ] submodule を更新する手順に従う\n         例: `ac-config/ac-migration`\n\n3. **リリースする**\n\n   - [ ] 以下のドキュメントに従ってリリースする\n         https://air-closet.esa.io/posts/733\n   - [ ] リリース後、確認する内容をチェック\n         例: `user_details.price_version` を追加した場合、追加されたことを確認する",
    "bodyEn": "## Release air-closet-migration\n\n#### 📝 Developer Entry\n\n| Item                                        | Value    |\n| ------------------------------------------- | -------- |\n| Execution time in STG environment           | XX [sec] |\n| Need after-hours release? (2:30am - 5:30am) | Yes / No |\n\n#### Steps\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-migration\n         https://github.com/air-closet/air-closet-ssr/pull/2825\n         Update the PR link as needed\n\n2. **Update submodules (if necessary)**\n\n   - [ ] Follow instructions to update submodules\n         Example: `ac-config/ac-migration`\n\n3. **Release**\n\n   - [ ] Follow instructions in the document\n         https://air-closet.esa.io/posts/733\n   - [ ] Verify release completion\n         Example: If `user_details.price_version` was added, confirm it exists",
    "bodyVi": "## Release air-closet-migration\n\n#### 📝 Developer Entry\n\n| Mục                                               | Giá trị   |\n| ------------------------------------------------- | --------- |\n| Thời gian thực thi trong môi trường STG           | XX [giây] |\n| Có cần release ngoài giờ không? (2:30am - 5:30am) | Yes / No  |\n\n#### Các bước\n\n1. **Merge PR bên dưới**\n\n   - [ ] air-closet-migration\n         https://github.com/air-closet/air-closet-ssr/pull/2825\n         Cần thay đổi link PR cho đúng\n\n2. **Cập nhật submodule (nếu cần)**\n\n   - [ ] Làm theo hướng dẫn để cập nhật submodule\n         Ví dụ: `ac-config/ac-migration`\n\n3. **Release**\n\n   - [ ] Làm theo hướng dẫn trong tài liệu\n         https://air-closet.esa.io/posts/733\n   - [ ] Kiểm tra xem release đã thành công\n         Ví dụ: Nếu `user_details.price_version` được thêm, xác nhận nó tồn tại"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-node-batch",
    "repo": "air-closet-node-batch",
    "bodyJa": "## air-closet-node-batch のリリース\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-node-batch\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         ※ PR リンクは必ず変更する\n\n2. **リリースする**\n\n   - [ ] リンク先の手順に従い production のステップ 1-5 を実行\n         https://air-closet.esa.io/posts/568\n   - [ ] 以下のバッチコマンドを順に実行\n     - [ ] `npm run release-np`\n     - [ ] `npm run release-warehouse`\n     - [ ] `npm run release-check-notify`\n     - [ ] `npm run release-service`\n     - [ ] `npm run release-hubspot`\n     - [ ] `npm run release-sql`\n\n3. **バッチサーバーが起動していることを確認する**\n\n   - [ ] np\n   - [ ] warehouse\n   - [ ] check-notify\n   - [ ] service\n   - [ ] hubspot\n   - [ ] sql\n   - 参考: [Slack 確認例](https://air-closet.slack.com/archives/C1RK1JU7K/p1729047371042329)\n\n4. **リリースできたことを確認する**\n   - [ ] `air-closet-node-batch-service-prod-amzlinux2` に入り、変更内容を確認\n         例: `src/tasks/user.js` の `_checkIsNeedPenaltyCreate` メソッドが存在すること\n         ※ プロジェクトごとに修正箇所を確認",
    "bodyEn": "## Release air-closet-node-batch\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-node-batch\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         Update the PR link as needed\n\n2. **Release**\n\n   - [ ] Follow the production steps 1-5 as described in the document\n         https://air-closet.esa.io/posts/568\n   - [ ] Run the batch commands in order\n     - [ ] `npm run release-np`\n     - [ ] `npm run release-warehouse`\n     - [ ] `npm run release-check-notify`\n     - [ ] `npm run release-service`\n     - [ ] `npm run release-hubspot`\n     - [ ] `npm run release-sql`\n\n3. **Check that the batch servers have started**\n\n   - [ ] np\n   - [ ] warehouse\n   - [ ] check-notify\n   - [ ] service\n   - [ ] hubspot\n   - [ ] sql\n   - Reference: [Slack example](https://air-closet.slack.com/archives/C1RK1JU7K/p1729047371042329)\n\n4. **Verify release**\n   - [ ] Log in to `air-closet-node-batch-service-prod-amzlinux2` and confirm changes\n         Example: `_checkIsNeedPenaltyCreate` method exists in `src/tasks/user.js`\n         ※ Specify the change to check per project",
    "bodyVi": "## Release air-closet-node-batch\n\n1. **Merge PR bên dưới**\n\n   - [ ] air-closet-node-batch\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         Cần thay đổi link PR cho đúng\n\n2. **Release**\n\n   - [ ] Làm theo các bước production 1-5 trong tài liệu\n         https://air-closet.esa.io/posts/568\n   - [ ] Chạy các lệnh batch theo thứ tự\n     - [ ] `npm run release-np`\n     - [ ] `npm run release-warehouse`\n     - [ ] `npm run release-check-notify`\n     - [ ] `npm run release-service`\n     - [ ] `npm run release-hubspot`\n     - [ ] `npm run release-sql`\n\n3. **Kiểm tra batch server đã khởi động**\n\n   - [ ] np\n   - [ ] warehouse\n   - [ ] check-notify\n   - [ ] service\n   - [ ] hubspot\n   - [ ] sql\n   - Tham khảo: [Slack ví dụ](https://air-closet.slack.com/archives/C1RK1JU7K/p1729047371042329)\n\n4. **Xác nhận release thành công**\n   - [ ] Vào `air-closet-node-batch-service-prod-amzlinux2` và xác nhận thay đổi\n         Ví dụ: `_checkIsNeedPenaltyCreate` có tồn tại trong `src/tasks/user.js`\n         ※ Ghi rõ nội dung cần kiểm tra theo từng dự án"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-tsnode-batch",
    "repo": "air-closet-tsnode-batch",
    "bodyJa": "## air-closet-tsnode-batch のリリース\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-tsnode-batch\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         ※ PR リンクは必ず変更する\n\n2. **リリースする**\n\n   - [ ] 以下のドキュメントの「本番」ステップ 1-3 を順に実行\n         https://github.com/air-closet/air-closet-batch-infrastructure?tab=readme-ov-file#%E6%9C%AC%E7%95%AA\n   - [ ] 環境変数の設定を実施\n     - [ ] docker-compose の environment に設定\n           例: `TIMEOUT: 3600000` （不要なら削除）\n     - [ ] ecs-params の secrets に設定\n           例: `STG_AC_SERVICE_DB_HOST: 192.168.0.1` （不要なら削除）\n   - [ ] 「本番」ステップ 4-8 を順に実行\n     - [ ] main\n     - [ ] recommend-fkus\n\n3. **リリースできたことを確認する**\n   - [ ] `ECS > クラスター > batch-prod > リリースしたサービスの task definition > JSON`\n         で image が最新の SHA1 のイメージであることを確認",
    "bodyEn": "## Release air-closet-tsnode-batch\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-tsnode-batch\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         Update the PR link as needed\n\n2. **Release**\n\n   - [ ] Execute steps 1-3 of \"Production\" in the document\n         https://github.com/air-closet/air-closet-batch-infrastructure?tab=readme-ov-file#%E6%9C%AC%E7%95%AA\n   - [ ] Set environment variables as described\n     - [ ] Configure docker-compose environment\n           e.g., `TIMEOUT: 3600000` (remove if unnecessary)\n     - [ ] Configure ecs-params secrets\n           e.g., `STG_AC_SERVICE_DB_HOST: 192.168.0.1` (remove if unnecessary)\n   - [ ] Execute steps 4-8 of \"Production\" for the release targets\n     - [ ] main\n     - [ ] recommend-fkus\n\n3. **Verify release**\n   - [ ] In `ECS > Cluster > batch-prod > Released service task definition > JSON`\n         confirm the image is the latest SHA1",
    "bodyVi": "## Release air-closet-tsnode-batch\n\n1. **Merge PR bên dưới**\n\n   - [ ] air-closet-tsnode-batch\n         https://github.com/air-closet/air-closet-styling-api/pull/xxxx\n         Cần thay đổi link PR cho đúng\n\n2. **Release**\n\n   - [ ] Thực hiện các bước 1-3 của \"Production\" trong tài liệu\n         https://github.com/air-closet/air-closet-batch-infrastructure?tab=readme-ov-file#%E6%9C%AC%E7%95%AA\n   - [ ] Cấu hình các biến môi trường\n     - [ ] docker-compose environment\n           ví dụ: `TIMEOUT: 3600000` (xóa nếu không cần)\n     - [ ] ecs-params secrets\n           ví dụ: `STG_AC_SERVICE_DB_HOST: 192.168.0.1` (xóa nếu không cần)\n   - [ ] Thực hiện các bước 4-8 của \"Production\" cho các release target\n     - [ ] main\n     - [ ] recommend-fkus\n\n3. **Xác nhận release**\n   - [ ] Trong `ECS > Cluster > batch-prod > Released service task definition > JSON`\n         kiểm tra image là SHA1 mới nhất"
  },
  {
    "category": "airCloset",
    "name": "Release air-closet-next-warehouse",
    "repo": "air-closet-next-warehouse",
    "bodyJa": "## air-closet-next-warehouse のリリース\n\n1. 以下の PR の「Merge pull request」を押下する\n\n   - [ ] air-closet-next-warehouse: https://github.com/air-closet/air-closet-next-warehouse/pull/820\n\n1. air-closet-infrastructure にリリース対象の SHA1 をセットする\n\n   - [ ] air-closet-infrastructure/ansible/group_vars 配下の対象ファイルの release_sha1 を最新の master の SHA1 に更新\n   - [ ] 以下を実行\n         `PROJECT_NO=AIRCLOSET-XXXXX <- 変更必須 / Điền mã project\ngit commit -am \":rocket:$PROJECT_NO: release to prod\"\ngit push origin master`\n\n1. プレ本番環境にリリースする\n\n   - [ ] リンク先の手順に従い `ac-next-warehouse-api-prod` をリリース\n         https://air-closet.esa.io/posts/1594#ansible%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B%E3%83%AC%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E3%83%97%E3%83%AC%E6%9C%AC%E7%95%AA%E7%92%B0%E5%A2%83%E3%81%AB%E5%87%BA%E3%81%99)\n\n1. プレ本番環境でテストする\n\n   - [ ] ログインできる\n   - [ ] 過去アイテムが表示され、購入ボタンが表示される\n   - URL: https://prod-black.air-closet.com/\n\n1. 本番環境にリリースする\n\n   - [ ] リンク先の手順に従い `ac-next-warehouse-api-prod` をリリース\n         https://air-closet.esa.io/posts/1594#ansible%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B%E3%83%AC%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E6%9C%AC%E7%95%AA%E7%92%B0%E5%A2%83%E3%81%AB%E5%87%BA%E3%81%99)\n   - [ ] 完了後ターミナルで下記を実行し、`X-Ac-Api-Revision` が master SHA1 と一致することを確認\n         `curl -s --dump-header - https://next-warehouse.air-closet.com/status | grep -i 'x-ac-api-revision' | awk '{print \"released SHA1: \" $2}' | tr -d '\\r'`\n\n1. 本番環境でテストする\n   - [ ] ログインできる\n   - [ ] 過去アイテムが表示され、購入ボタンが表示される",
    "bodyEn": "## Release air-closet-next-warehouse\n\n1. Click \"Merge pull request\" on the following PR\n\n   - [ ] air-closet-next-warehouse: https://github.com/air-closet/air-closet-next-warehouse/pull/820\n\n1. Set release SHA1 in air-closet-infrastructure\n\n   - [ ] Update release_sha1 in the target file under air-closet-infrastructure/ansible/group_vars to the latest master SHA1\n   - [ ] Execute the following\n         `PROJECT_NO=AIRCLOSET-XXXXX <- update project code\ngit commit -am \":rocket:$PROJECT_NO: release to prod\"\ngit push origin master`\n\n1. Release to pre-production\n\n   - [ ] Follow the guide to release `ac-next-warehouse-api-prod`\n         https://air-closet.esa.io/posts/1594#ansible%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B%E3%83%AC%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E3%83%97%E3%83%AC%E6%9C%AC%E7%95%AA%E7%92%B0%E5%A2%83%E3%81%AB%E5%87%BA%E3%81%99)\n\n1. Test in pre-production\n\n   - [ ] Can log in\n   - [ ] Past items display and purchase button shows\n   - URL: https://prod-black.air-closet.com/\n\n1. Release to production\n\n   - [ ] Follow the guide to release `ac-next-warehouse-api-prod`\n         https://air-closet.esa.io/posts/1594#ansible%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B%E3%83%AC%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E6%9C%AC%E7%95%AA%E7%92%B0%E5%A2%83%E3%81%AB%E5%87%BA%E3%81%99)\n   - [ ] After completion, run the following in terminal to confirm `X-Ac-Api-Revision` matches master SHA1\n         curl -s --dump-header - https://next-warehouse.air-closet.com/status | grep -i 'x-ac-api-revision' | awk '{print \"released SHA1: \" $2}' | tr -d '\\r'\n\n1. Test in production\n   - [ ] Can log in\n   - [ ] Past items display and purchase button shows",
    "bodyVi": "## Release air-closet-next-warehouse\n\n1. Nhấn \"Merge pull request\" trên PR sau\n\n   - [ ] air-closet-next-warehouse: https://github.com/air-closet/air-closet-next-warehouse/pull/820\n\n1. Cập nhật SHA1 release trong air-closet-infrastructure\n\n   - [ ] Cập nhật release_sha1 trong file target dưới air-closet-infrastructure/ansible/group_vars với SHA1 mới nhất của master\n   - [ ] Thực hiện các lệnh sau\n         `PROJECT_NO=AIRCLOSET-XXXXX <- cập nhật mã dự án\ngit commit -am \":rocket:$PROJECT_NO: release to prod\"\ngit push origin master`\n\n1. Release lên pre-production\n\n   - [ ] Thực hiện theo hướng dẫn để release `ac-next-warehouse-api-prod`\n         https://air-closet.esa.io/posts/1594#ansible%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B%E3%83%AC%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E3%83%97%E3%83%AC%E6%9C%AC%E7%95%AA%E7%92%B0%E5%A2%83%E3%81%AB%E5%87%BA%E3%81%99)\n\n1. Kiểm tra trên pre-production\n\n   - [ ] Đăng nhập được\n   - [ ] Hiển thị các món trước đó và nút mua hiển thị\n   - URL: https://prod-black.air-closet.com/\n\n1. Release lên production\n\n   - [ ] Thực hiện theo hướng dẫn để release `ac-next-warehouse-api-prod`\n         https://air-closet.esa.io/posts/1594#ansible%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B%E3%83%AC%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E6%9C%AC%E7%95%AA%E7%92%B0%E5%A2%83%E3%81%AB%E5%87%BA%E3%81%99)\n   - [ ] Sau khi hoàn tất, chạy lệnh sau để xác nhận `X-Ac-Api-Revision` trùng với SHA1 của master\n         curl -s --dump-header - https://next-warehouse.air-closet.com/status | grep -i 'x-ac-api-revision' | awk '{print \"released SHA1: \" $2}' | tr -d '\\r'\n\n1. Kiểm tra trên production\n   - [ ] Đăng nhập được\n   - [ ] Hiển thị các món trước đó và nút mua hiển thị"
  },
  {
    "category": "airCloset",
    "name": "Release Arthur",
    "repo": "Arthur",
    "bodyJa": "## Arthur のリリース\n\n1. **以下の PR をマージする**\n\n   - [ ] Arthur\n         https://github.com/air-closet/Arthur/pull/??\n         ※ PR 番号を入力\n\n2. **リリースコマンドを実行する**\n\n   - [ ] ローカル環境で以下を実行\n         ```bash\n     yarn deploy:prod\n     ```\n\n3. **リリースが完了したことを確認する**\n   - [ ] `ECS > Task Definitions > arthur > 対象サービスの Task Definition > JSON`\n         イメージの SHA1 が最新のものになっていることを確認",
    "bodyEn": "## Release Arthur\n\n1. **Merge the following PR**\n\n   - [ ] Arthur\n         https://github.com/air-closet/Arthur/pull/??\n         Replace with the actual PR number\n\n2. **Run the release command**\n\n   - [ ] Execute in your local environment\n         ```bash\n     yarn deploy:prod\n     ```\n\n3. **Confirm release completion**\n   - [ ] `ECS > Task Definitions > arthur > Task Definition > JSON`\n         Verify that the image uses the latest SHA1 hash",
    "bodyVi": "## Release Arthur\n\n1. **Merge PR bên dưới**\n\n   - [ ] Arthur\n         https://github.com/air-closet/Arthur/pull/??\n         Thay bằng số PR thực tế\n\n2. **Chạy lệnh release**\n\n   - [ ] Thực hiện trên môi trường local\n         ```bash\n     yarn deploy:prod\n     ```\n\n3. **Xác nhận release hoàn tất**\n   - [ ] `ECS > Task Definitions > arthur > Task Definition > JSON`\n         Xác nhận rằng image sử dụng SHA1 mới nhất"
  },
  {
    "category": "airCloset",
    "name": "Maintenance Mode",
    "repo": "",
    "bodyJa": "1. **対象インスタンスを確認する**\n\n   - [ ] [air-closet-ssr-prod-nlb-80](https://ap-northeast-1.console.aws.amazon.com/ec2/home?region=ap-northeast-1#TargetGroup:targetGroupArn=arn:aws:elasticloadbalancing:ap-northeast-1:784286759117:targetgroup/air-closet-ssr-prod-nlb-80/b079284158d66417) に紐づいたインスタンスの末尾の番号を確認\n\n2. **全てのインスタンスに対して実施する**\n\n   - [ ] ac-ssr-X1\n   - [ ] ac-ssr-X2\n\n   各インスタンスで以下を実行:\n\n   ```bash\n   sudo su - ec2-user; sudo su root; cd /etc/nginx/conf.d; sed -e 's/\\/var\\/tmp\\/nginx\\/maintenane/\\/var\\/tmp/g' vhosts.conf > ~/tmp.conf; sudo rm -f vhosts.conf; sudo mv ~/tmp.conf ./vhosts.conf; sudo nginx -s reload;\n   ```\n\n3. **メンテナンスモードを確認**\n   - [ ] https://www.air-closet.com/ にアクセスし、メンテナンスモードに入っていることを確認\n   - もしメンテナンスモードに入っていなければ `sudo nginx -s reload` を再実行",
    "bodyEn": "1. **Identify target instances**\n\n   - [ ] Check instance numbers linked to [air-closet-ssr-prod-nlb-80](https://ap-northeast-1.console.aws.amazon.com/ec2/home?region=ap-northeast-1#TargetGroup:targetGroupArn=arn:aws:elasticloadbalancing:ap-northeast-1:784286759117:targetgroup/air-closet-ssr-prod-nlb-80/b079284158d66417)\n\n2. **Execute on all instances**\n\n   - [ ] ac-ssr-X1\n   - [ ] ac-ssr-X2\n\n   Run on each instance:\n\n   ```bash\n   sudo su - ec2-user; sudo su root; cd /etc/nginx/conf.d; sed -e 's/\\/var\\/tmp\\/nginx\\/maintenane/\\/var\\/tmp/g' vhosts.conf > ~/tmp.conf; sudo rm -f vhosts.conf; sudo mv ~/tmp.conf ./vhosts.conf; sudo nginx -s reload;\n   ```\n\n3. **Verify maintenance mode**\n   - [ ] Access https://www.air-closet.com/ and confirm maintenance mode is active\n   - If not in maintenance mode, re-run `sudo nginx -s reload`",
    "bodyVi": "1. **Xác định instance cần thực hiện**\n\n   - [ ] Kiểm tra số instance được liên kết với [air-closet-ssr-prod-nlb-80](https://ap-northeast-1.console.aws.amazon.com/ec2/home?region=ap-northeast-1#TargetGroup:targetGroupArn=arn:aws:elasticloadbalancing:ap-northeast-1:784286759117:targetgroup/air-closet-ssr-prod-nlb-80/b079284158d66417)\n\n2. **Thực hiện trên tất cả instance**\n\n   - [ ] ac-ssr-X1\n   - [ ] ac-ssr-X2\n\n   Chạy trên mỗi instance:\n\n   ```bash\n   sudo su - ec2-user; sudo su root; cd /etc/nginx/conf.d; sed -e 's/\\/var\\/tmp\\/nginx\\/maintenane/\\/var\\/tmp/g' vhosts.conf > ~/tmp.conf; sudo rm -f vhosts.conf; sudo mv ~/tmp.conf ./vhosts.conf; sudo nginx -s reload;\n   ```\n\n3. **Xác nhận chế độ bảo trì**\n   - [ ] Truy cập https://www.air-closet.com/ và xác nhận đang ở chế độ bảo trì\n   - Nếu chưa vào được, chạy lại `sudo nginx -s reload`"
  },
  {
    "category": "Bridge",
    "name": "Release bridge-api",
    "repo": "bridge-api",
    "bodyJa": "**1. Pull Request のマージ**\n\n- [ ] **bridge-api**: https://github.com/air-closet/bridge-api/pull/xxx\n\n**2. AWS CLI を使ったビルド & デプロイ**\n\n```bash\n# SSM 経由でサービス一覧を表示\nssm-start-session\n\n# 'bridge-deploy' サービスを選択\nbridge-deploy\n\n# ec2-user アカウントに切り替え\nsudo su - ec2-user\n\n# ecspresso ディレクトリへ移動\ncd bridge-api/ecspresso\n\n# 本番環境向けデプロイスクリプトを実行\nsh deploy.sh prod\n```",
    "bodyEn": "**1. Merge Pull Request**\n\n- [ ] **bridge-api**: https://github.com/air-closet/bridge-api/pull/xxx\n\n**2. Build & Deploy via AWS CLI**\n\n```bash\n# List available services through SSM\nssm-start-session\n\n# Select the 'bridge-deploy' service\nbridge-deploy\n\n# Switch to the ec2-user account\nsudo su - ec2-user\n\n# Move to the ecspresso directory\ncd bridge-api/ecspresso\n\n# Run the deploy script for the production environment\nsh deploy.sh prod\n```",
    "bodyVi": "**1. Merge Pull Request**\n\n- [ ] **bridge-api**: https://github.com/air-closet/bridge-api/pull/xxx\n\n**2. Build & Deploy bằng AWS CLI**\n\n```bash\n# Liệt kê các service qua SSM\nssm-start-session\n\n# Chọn service 'bridge-deploy'\nbridge-deploy\n\n# Đổi sang tài khoản ec2-user\nsudo su - ec2-user\n\n# Di chuyển đến thư mục ecspresso\ncd bridge-api/ecspresso\n\n# Chạy script deploy lên môi trường production\nsh deploy.sh prod\n```"
  },
  {
    "category": "Bridge",
    "name": "Release bridge-infrastructure",
    "repo": "bridge-infrastructure",
    "bodyJa": "**1. Pull Request のマージ**\n\n- [ ] **bridge-infrastructure**: https://github.com/air-closet/bridge-infrastructure/pull/109\n\n**2. AWS CLI を使ったビルド & デプロイ**\n\n```bash\n# SSM 経由でサービス一覧を表示\nssm-start-session\n\n# 'bridge-deploy' サービスを選択\nbridge-deploy\n\n# ec2-user アカウントに切り替え\nsudo su - ec2-user\n\n# bridge-infrastructure ディレクトリへ移動\ncd /bridge-infrastructure\n\n# 開発中のフィーチャーブランチをチェックアウトし、最新コードを取得\ngit checkout <feature-branch>\ngit pull\n\n# Lambda 関数に変更がある場合は、各 Lambda コードディレクトリの\n# 手順に従って再ビルドしてください\n\n# 本番環境の terraform state ディレクトリへ移動\ncd bridge-infrastructure/terraform/services/bridge/production/\n\n# 競合を避けるため、古い terraform providers を削除\nfind /home/ec2-user/bridge-infrastructure -path \"*/.terraform/providers\" -exec rm -rf {} +\n\n# terraform を再初期化(プロバイダーをアップグレード)\nterraform init -upgrade\n\n# デプロイ前に実行計画を確認 — 変更内容を必ず慎重にレビュー\nterraform plan\n\n# 本番環境へ変更を適用\nterraform apply\n```\n\n> ⚠️ **注意**: `terraform apply` を実行する前に、必ず `terraform plan` の出力を慎重にレビューしてください。特にリソースの `destroy` や `replace` 操作には十分注意してください。",
    "bodyEn": "**1. Merge Pull Request**\n\n- [ ] **bridge-infrastructure**: https://github.com/air-closet/bridge-infrastructure/pull/109\n\n**2. Build & Deploy via AWS CLI**\n\n```bash\n# List available services through SSM\nssm-start-session\n\n# Select the 'bridge-deploy' service\nbridge-deploy\n\n# Switch to the ec2-user account\nsudo su - ec2-user\n\n# Move to the bridge-infrastructure directory\ncd /bridge-infrastructure\n\n# Checkout the feature branch and pull the latest code\ngit checkout <feature-branch>\ngit pull\n\n# If any Lambda functions have changed, rebuild them\n# following the instructions in their respective Lambda code directories\n\n# Move to the terraform state directory for the production environment\ncd bridge-infrastructure/terraform/services/bridge/production/\n\n# Remove old terraform providers to avoid conflicts\nfind /home/ec2-user/bridge-infrastructure -path \"*/.terraform/providers\" -exec rm -rf {} +\n\n# Re-initialize terraform (with provider upgrade)\nterraform init -upgrade\n\n# Review the execution plan before deploying — CHECK CHANGES CAREFULLY\nterraform plan\n\n# Apply the changes to production\nterraform apply\n```\n\n> ⚠️ **Note**: Always carefully review the `terraform plan` output before running `terraform apply`. Pay special attention to any `destroy` or `replace` operations on resources.",
    "bodyVi": "**1. Merge Pull Request**\n\n- [ ] **bridge-infrastructure**: https://github.com/air-closet/bridge-infrastructure/pull/109\n\n**2. Build & Deploy bằng AWS CLI**\n\n```bash\n# Liệt kê các service qua SSM\nssm-start-session\n\n# Chọn service 'bridge-deploy'\nbridge-deploy\n\n# Đổi sang tài khoản ec2-user\nsudo su - ec2-user\n\n# Di chuyển đến thư mục bridge-infrastructure\ncd /bridge-infrastructure\n\n# Checkout nhánh feature đang phát triển và cập nhật code mới nhất\ngit checkout <feature-branch>\ngit pull\n\n# Nếu có thay đổi Lambda function, build lại theo hướng dẫn\n# trong thư mục chứa code Lambda tương ứng\n\n# Di chuyển đến thư mục terraform state của môi trường production\ncd bridge-infrastructure/terraform/services/bridge/production/\n\n# Xoá các terraform providers cũ để tránh xung đột\nfind /home/ec2-user/bridge-infrastructure -path \"*/.terraform/providers\" -exec rm -rf {} +\n\n# Khởi tạo lại terraform (kèm upgrade providers)\nterraform init -upgrade\n\n# Kiểm tra plan trước khi deploy — REVIEW KỸ các thay đổi\nterraform plan\n\n# Triển khai thay đổi lên production\nterraform apply\n```\n\n> ⚠️ **Lưu ý**: Luôn review kỹ output của `terraform plan` trước khi chạy `terraform apply`. Đặc biệt chú ý các thao tác `destroy` hoặc `replace` resource."
  },
  {
    "category": "Mall",
    "name": "Release acm-web",
    "repo": "acm-web",
    "bodyJa": "## acm-web をリリースする\n\n0. **Black 環境にて最低限の機能の動作確認を行う**\n\n   - [ ] ブラック環境にリリース\n         ```bash\n         yarn prod-sync-assets  # CDNに画像をアップロードする場合\n         yarn black\n         ```\n         ※ CDN への画像ファイルアップロードが必要な場合は、別途対応が必要です。\n\n   - [ ] ブラック環境で動作確認\n         手順：https://air-closet.esa.io/posts/2646\n\n1. **以下の PR をマージする**\n\n   - [ ] acm-web\n         https://github.com/air-closet/acm-web/pull/??\n         ※ PR 番号を入力\n\n2. **本番にリリースする**\n\n   - [ ] 以下のコマンドを実行する\n         ```bash\n         git checkout master\n         git pull origin master\n         yarn prod\n         ```\n\n   - [ ] リリースコマンド内で表示される SHA1 が最新の master の SHA1 と一致している\n\n3. **リリースできているかの確認**\n\n   - [ ] 新機能が正しく動作することを確認\n         ※ 確認項目を記載\n\n4. **リリース後に以下の内容を確認する**\n\n   - [ ] ログインができる\n   - [ ] レンタルができる\n   - [ ] レンタルのキャンセルができる",
    "bodyEn": "## Release acm-web\n\n0. **Verify minimum functionality in Black environment**\n\n   - [ ] Release to Black environment\n         ```bash\n         yarn prod-sync-assets  # If uploading images to CDN\n         yarn black\n         ```\n         ※ Additional steps required if uploading image files to CDN.\n\n   - [ ] Verify functionality in Black environment\n         Guide: https://air-closet.esa.io/posts/2646\n\n1. **Merge the following PR**\n\n   - [ ] acm-web\n         https://github.com/air-closet/acm-web/pull/??\n         ※ Enter PR number\n\n2. **Release to production**\n\n   - [ ] Execute the following commands\n         ```bash\n         git checkout master\n         git pull origin master\n         yarn prod\n         ```\n\n   - [ ] Confirm the SHA1 displayed in the release command matches the latest master SHA1\n\n3. **Confirm release was successful**\n\n   - [ ] Verify new features work correctly\n         ※ Enter items to check\n\n4. **Post-release verification**\n\n   - [ ] Login works\n   - [ ] Rental works\n   - [ ] Rental cancellation works",
    "bodyVi": "## Release acm-web\n\n0. **Kiểm tra chức năng cơ bản trên môi trường Black**\n\n   - [ ] Release lên môi trường Black\n         ```bash\n         yarn prod-sync-assets  # Nếu upload ảnh lên CDN\n         yarn black\n         ```\n         ※ Cần xử lý riêng nếu upload file ảnh lên CDN.\n\n   - [ ] Kiểm tra hoạt động trên môi trường Black\n         Hướng dẫn: https://air-closet.esa.io/posts/2646\n\n1. **Merge PR sau**\n\n   - [ ] acm-web\n         https://github.com/air-closet/acm-web/pull/??\n         ※ Điền số PR\n\n2. **Release lên production**\n\n   - [ ] Chạy các lệnh sau\n         ```bash\n         git checkout master\n         git pull origin master\n         yarn prod\n         ```\n\n   - [ ] Xác nhận SHA1 hiển thị trong lệnh release trùng với SHA1 mới nhất của master\n\n3. **Xác nhận đã release thành công**\n\n   - [ ] Xác nhận chức năng mới hoạt động đúng\n         ※ Điền mục cần check\n\n4. **Xác nhận sau khi release**\n\n   - [ ] Đăng nhập được\n   - [ ] Thuê được\n   - [ ] Hủy thuê được"
  },
  {
    "category": "Mall",
    "name": "Release acm-api",
    "repo": "acm-api",
    "bodyJa": "## acm-api をリリースする\n\n0. **Black 環境にて最低限の機能の動作確認を行う**\n\n   - [ ] ブラック環境にリリース\n         ```bash\n         yarn release-black\n         ```\n         ※ CDN への画像ファイルアップロードが必要な場合は、別途対応が必要です。\n\n   - [ ] ブラック環境で動作確認\n         手順：https://air-closet.esa.io/posts/2646\n\n1. **以下の PR をマージする**\n\n   - [ ] acm-api\n         https://github.com/air-closet/acm-api/pull/??\n         ※ PR 番号を入力\n\n2. **本番にリリースする**\n\n   - [ ] 以下のコマンドを実行する\n         ```bash\n         git checkout master\n         git pull origin master\n         yarn release-prod\n         ```\n\n   - [ ] リリースコマンド内で表示される SHA1 が最新の master の SHA1 と一致している\n\n3. **リリースできているかの確認**\n\n   - [ ] 以下のコマンドを実行し、リリースされている SHA1 が最新の master の SHA1 と一致することを確認する\n         ```bash\n         SERVICE_DESC=$(aws ecs describe-services --cluster acm-api-prod-20191106 --services acm-api)\n         TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')\n         TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)\n         IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')\n         SHA1=$(echo $IMAGE_URL | cut -d \"_\" -f 2)\n         echo \"\\nSHA1: $SHA1\\n\"\n         ```\n\n4. **リリース後に以下の内容を確認する**\n\n   - [ ] ログインができる\n   - [ ] レンタルができる\n   - [ ] レンタルのキャンセルができる",
    "bodyEn": "## Release acm-api\n\n0. **Verify minimum functionality in Black environment**\n\n   - [ ] Release to Black environment\n         ```bash\n         yarn release-black\n         ```\n         ※ Additional steps required if uploading image files to CDN.\n\n   - [ ] Verify functionality in Black environment\n         Guide: https://air-closet.esa.io/posts/2646\n\n1. **Merge the following PR**\n\n   - [ ] acm-api\n         https://github.com/air-closet/acm-api/pull/??\n         ※ Enter PR number\n\n2. **Release to production**\n\n   - [ ] Execute the following commands\n         ```bash\n         git checkout master\n         git pull origin master\n         yarn release-prod\n         ```\n\n   - [ ] Confirm the SHA1 displayed in the release command matches the latest master SHA1\n\n3. **Confirm release was successful**\n\n   - [ ] Execute the following command and confirm the deployed SHA1 matches the latest master SHA1\n         ```bash\n         SERVICE_DESC=$(aws ecs describe-services --cluster acm-api-prod-20191106 --services acm-api)\n         TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')\n         TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)\n         IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')\n         SHA1=$(echo $IMAGE_URL | cut -d \"_\" -f 2)\n         echo \"\\nSHA1: $SHA1\\n\"\n         ```\n\n4. **Post-release verification**\n\n   - [ ] Login works\n   - [ ] Rental works\n   - [ ] Rental cancellation works",
    "bodyVi": "## Release acm-api\n\n0. **Kiểm tra chức năng cơ bản trên môi trường Black**\n\n   - [ ] Release lên môi trường Black\n         ```bash\n         yarn release-black\n         ```\n         ※ Cần xử lý riêng nếu upload file ảnh lên CDN.\n\n   - [ ] Kiểm tra hoạt động trên môi trường Black\n         Hướng dẫn: https://air-closet.esa.io/posts/2646\n\n1. **Merge PR sau**\n\n   - [ ] acm-api\n         https://github.com/air-closet/acm-api/pull/??\n         ※ Điền số PR\n\n2. **Release lên production**\n\n   - [ ] Chạy các lệnh sau\n         ```bash\n         git checkout master\n         git pull origin master\n         yarn release-prod\n         ```\n\n   - [ ] Xác nhận SHA1 hiển thị trong lệnh release trùng với SHA1 mới nhất của master\n\n3. **Xác nhận đã release thành công**\n\n   - [ ] Chạy lệnh sau và xác nhận SHA1 đã deploy trùng với SHA1 mới nhất của master\n         ```bash\n         SERVICE_DESC=$(aws ecs describe-services --cluster acm-api-prod-20191106 --services acm-api)\n         TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')\n         TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)\n         IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')\n         SHA1=$(echo $IMAGE_URL | cut -d \"_\" -f 2)\n         echo \"\\nSHA1: $SHA1\\n\"\n         ```\n\n4. **Xác nhận sau khi release**\n\n   - [ ] Đăng nhập được\n   - [ ] Thuê được\n   - [ ] Hủy thuê được"
  },
  {
    "category": "Mall",
    "name": "Release acm-admin-web",
    "repo": "acm-admin-web",
    "bodyJa": "## acm-admin-web をリリースする\n\n1. **以下の PR をマージする**\n\n   - [ ] acm-admin-web\n         https://github.com/air-closet/acm-admin-web/pull/??\n         ※ PR 番号を入力\n\n2. **本番にリリースする**\n\n   - [ ] 以下のコマンドを実行する\n         ```bash\n         git checkout master_v2\n         git pull origin master_v2\n         yarn prod\n         ```\n\n3. **リリース後に以下の内容を確認する**\n\n   PL（Jawa さん）に以下の内容を確認してもらう：\n   - [ ] ログインができる\n   - [ ] ユーザー一覧にユーザーが表示される\n   - [ ] 新しい機能がリリースできている",
    "bodyEn": "## Release acm-admin-web\n\n1. **Merge the following PR**\n\n   - [ ] acm-admin-web\n         https://github.com/air-closet/acm-admin-web/pull/??\n         ※ Enter PR number\n\n2. **Release to production**\n\n   - [ ] Execute the following commands\n         ```bash\n         git checkout master_v2\n         git pull origin master_v2\n         yarn prod\n         ```\n\n3. **Post-release verification**\n\n   Have PL (Jawa-san) verify the following:\n   - [ ] Login works\n   - [ ] User list displays users\n   - [ ] New features are released",
    "bodyVi": "## Release acm-admin-web\n\n1. **Merge PR sau**\n\n   - [ ] acm-admin-web\n         https://github.com/air-closet/acm-admin-web/pull/??\n         ※ Điền số PR\n\n2. **Release lên production**\n\n   - [ ] Chạy các lệnh sau\n         ```bash\n         git checkout master_v2\n         git pull origin master_v2\n         yarn prod\n         ```\n\n3. **Xác nhận sau khi release**\n\n   Nhờ PL (Jawa-san) xác nhận các mục sau:\n   - [ ] Đăng nhập được\n   - [ ] Danh sách user hiển thị đúng\n   - [ ] Chức năng mới đã release thành công"
  },
  {
    "category": "Mall",
    "name": "Release acm-admin-api",
    "repo": "acm-admin-api",
    "bodyJa": "## acm-admin-api をリリースする\n\n1. **以下の PR をマージする**\n\n   - [ ] acm-admin-api\n         https://github.com/air-closet/acm-admin-api/pull/??\n         ※ PR 番号を入力\n\n2. **本番にリリースする**\n\n   - [ ] release コマンドを実行する\n         ```bash\n         git checkout master_v2\n         git pull origin master_v2\n         yarn build\n         cd ecspresso/\n         sh migration.sh prod\n         sh deploy.sh prod\n         ```\n\n   - [ ] リリースコマンド内で表示される SHA1 が最新の master の SHA1 と一致している\n\n3. **リリースできているかの確認**\n\n   - [ ] 以下のコマンドを実行し、リリースされている SHA1 が最新の master の SHA1 と一致することを確認する\n         ```bash\n         SERVICE_DESC=$(aws ecs describe-services --cluster acm-admin-api-prod-20200522 --services acm-admin-api-prod-v2)\n         TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')\n         TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)\n         IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')\n         SHA1=$(echo $IMAGE_URL | cut -d \":\" -f 2)\n         echo \"\\nSHA1: $SHA1\\n\"\n         ```\n\n4. **リリース後に以下の内容を確認する**\n\n   PL（Jawa さん）に以下の内容を確認してもらう：\n   - [ ] ログインができる\n   - [ ] ユーザー一覧にユーザーが表示される\n   - [ ] 新しい機能がリリースできている",
    "bodyEn": "## Release acm-admin-api\n\n1. **Merge the following PR**\n\n   - [ ] acm-admin-api\n         https://github.com/air-closet/acm-admin-api/pull/??\n         ※ Enter PR number\n\n2. **Release to production**\n\n   - [ ] Execute the release commands\n         ```bash\n         git checkout master_v2\n         git pull origin master_v2\n         yarn build\n         cd ecspresso/\n         sh migration.sh prod\n         sh deploy.sh prod\n         ```\n\n   - [ ] Confirm the SHA1 displayed in the release command matches the latest master SHA1\n\n3. **Confirm release was successful**\n\n   - [ ] Execute the following command and confirm the deployed SHA1 matches the latest master SHA1\n         ```bash\n         SERVICE_DESC=$(aws ecs describe-services --cluster acm-admin-api-prod-20200522 --services acm-admin-api-prod-v2)\n         TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')\n         TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)\n         IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')\n         SHA1=$(echo $IMAGE_URL | cut -d \":\" -f 2)\n         echo \"\\nSHA1: $SHA1\\n\"\n         ```\n\n4. **Post-release verification**\n\n   Have PL (Jawa-san) verify the following:\n   - [ ] Login works\n   - [ ] User list displays users\n   - [ ] New features are released",
    "bodyVi": "## Release acm-admin-api\n\n1. **Merge PR sau**\n\n   - [ ] acm-admin-api\n         https://github.com/air-closet/acm-admin-api/pull/??\n         ※ Điền số PR\n\n2. **Release lên production**\n\n   - [ ] Chạy các lệnh release\n         ```bash\n         git checkout master_v2\n         git pull origin master_v2\n         yarn build\n         cd ecspresso/\n         sh migration.sh prod\n         sh deploy.sh prod\n         ```\n\n   - [ ] Xác nhận SHA1 hiển thị trong lệnh release trùng với SHA1 mới nhất của master\n\n3. **Xác nhận đã release thành công**\n\n   - [ ] Chạy lệnh sau và xác nhận SHA1 đã deploy trùng với SHA1 mới nhất của master\n         ```bash\n         SERVICE_DESC=$(aws ecs describe-services --cluster acm-admin-api-prod-20200522 --services acm-admin-api-prod-v2)\n         TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')\n         TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)\n         IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')\n         SHA1=$(echo $IMAGE_URL | cut -d \":\" -f 2)\n         echo \"\\nSHA1: $SHA1\\n\"\n         ```\n\n4. **Xác nhận sau khi release**\n\n   Nhờ PL (Jawa-san) xác nhận các mục sau:\n   - [ ] Đăng nhập được\n   - [ ] Danh sách user hiển thị đúng\n   - [ ] Chức năng mới đã release thành công"
  },
  {
    "category": "Mall",
    "name": "Release acm-infra",
    "repo": "acm-infra",
    "bodyJa": "1. **以下の PR をマージする**\n\n   - [ ] acm-infra\n         https://github.com/air-closet/acm-infra/pull/??\n         ※ PR 番号を入力\n\n2. **本番にリリースする**\n\n   - [ ] 以下のコマンドを実行する\n         ```bash\n         git checkout master\n         git pull origin master\n         cd payment-batch/ecrobo-batch\n         make release-prod\n         ```\n\n3. **新しいバージョンを ECR にアップロードする**\n\n   - [ ] README.md に従って実行\n\n4. **リビジョンを変更する**\n\n   - [ ] タスクフォルダに移動する\n         ```bash\n         cd <acm-api/ecrobo-batch/payment-batch>/deploy/prod\n         ```\n\n   - [ ] リビジョン変更コマンドを実行する\n         ```bash\n         ./update-task.sh\n         ```\n\n   - [ ] 更新するタスクとバージョンを選択\n         例: `ecrobo_order: arn:aws:ecs:ap-northeast-1:784286759117:task-definition/acm-infra-ecrobo-batch-prod:195`\n\n   - [ ] タスク、現在のリビジョン、更新リビジョンを確認\n\n5. **リリースできているかの確認**\n\n   - [ ] スクリプトは正常に実行され、新しいリビジョンが表示される\n   - [ ] 可能であれば、AWS コンソールの画面を確認する\n\n#### 新しいバッチを追加する場合\n\n- [ ] AWS に新しいバッチを追加\n  1. https://ap-northeast-1.console.aws.amazon.com/ecs/v2/clusters/acm-infra-prod-20191107/scheduled-tasks/create にアクセス\n  2. 以下の内容を入力:\n     ```\n     Schedule rule name:\n     Scheduled rule description:\n     Schedule rule: turned on\n     Cron expression: cron(0 17 * * ? *)\n     Target ID:\n     Task definition family: acm-infra-payment-batch-prod/acm-infra-ecrobo-batch-prod\n     Task definition revision: latest\n     VPC: acm-prod-vpc\n     subnet: acm-prod-public-1a, acm-prod-public-1c\n     Security group: Use an existing security group\n     Security group name: acm-infra-prod-sg\n     Public IP: turned on\n     Container overrides の Command override で command をコピー\n     （<./payment,process_user_blacklist or ./ecrobo,stop_rental>）\n     Environment variable overrides: key (ENV) value (production)\n     ```",
    "bodyEn": "1. **Merge the following PR**\n\n   - [ ] acm-infra\n         https://github.com/air-closet/acm-infra/pull/??\n         ※ Enter PR number\n\n2. **Release to production**\n\n   - [ ] Execute the following commands\n         ```bash\n         git checkout master\n         git pull origin master\n         cd payment-batch/ecrobo-batch\n         make release-prod\n         ```\n\n3. **Upload new version to ECR**\n\n   - [ ] Follow README.md instructions\n\n4. **Update revision**\n\n   - [ ] Navigate to task directory\n         ```bash\n         cd <acm-api/ecrobo-batch/payment-batch>/deploy/prod\n         ```\n\n   - [ ] Run update revision command\n         ```bash\n         ./update-task.sh\n         ```\n\n   - [ ] Select task and version to update\n         E.g: `ecrobo_order: arn:aws:ecs:ap-northeast-1:784286759117:task-definition/acm-infra-ecrobo-batch-prod:195`\n\n   - [ ] Confirm task, current revision, and update revision\n\n5. **Confirm release was successful**\n\n   - [ ] Script executed successfully and new revision is displayed\n   - [ ] If possible, check revision on AWS console screen\n\n#### Adding a new batch\n\n- [ ] Add new batch to AWS\n  1. Go to https://ap-northeast-1.console.aws.amazon.com/ecs/v2/clusters/acm-infra-prod-20191107/scheduled-tasks/create\n  2. Fill in with details:\n     ```\n     Schedule rule name:\n     Scheduled rule description:\n     Schedule rule: turned on\n     Cron expression: cron(0 17 * * ? *)\n     Target ID:\n     Task definition family: acm-infra-payment-batch-prod/acm-infra-ecrobo-batch-prod\n     Task definition revision: latest\n     VPC: acm-prod-vpc\n     subnet: acm-prod-public-1a, acm-prod-public-1c\n     Security group: Use an existing security group\n     Security group name: acm-infra-prod-sg\n     Public IP: turned on\n     Container overrides Command override: copy command\n     (<./payment,process_user_blacklist or ./ecrobo,stop_rental>)\n     Environment variable overrides: key (ENV) value (production)\n     ```",
    "bodyVi": "1. **Merge PR sau**\n\n   - [ ] acm-infra\n         https://github.com/air-closet/acm-infra/pull/??\n         ※ Điền số PR\n\n2. **Release lên production**\n\n   - [ ] Chạy các lệnh sau\n         ```bash\n         git checkout master\n         git pull origin master\n         cd payment-batch/ecrobo-batch\n         make release-prod\n         ```\n\n3. **Upload phiên bản mới lên ECR**\n\n   - [ ] Thực hiện theo README.md\n\n4. **Update revision**\n\n   - [ ] Di chuyển đến thư mục task\n         ```bash\n         cd <acm-api/ecrobo-batch/payment-batch>/deploy/prod\n         ```\n\n   - [ ] Chạy lệnh update revision\n         ```bash\n         ./update-task.sh\n         ```\n\n   - [ ] Chọn task và version cần update\n         VD: `ecrobo_order: arn:aws:ecs:ap-northeast-1:784286759117:task-definition/acm-infra-ecrobo-batch-prod:195`\n\n   - [ ] Xác nhận task, revision hiện tại và revision mới\n\n5. **Xác nhận đã release thành công**\n\n   - [ ] Script chạy thành công và hiển thị revision mới\n   - [ ] Nếu có thể, kiểm tra revision trên màn hình AWS console\n\n#### Thêm batch mới\n\n- [ ] Thêm batch mới vào AWS\n  1. Truy cập https://ap-northeast-1.console.aws.amazon.com/ecs/v2/clusters/acm-infra-prod-20191107/scheduled-tasks/create\n  2. Điền các thông tin sau:\n     ```\n     Schedule rule name:\n     Scheduled rule description:\n     Schedule rule: turned on\n     Cron expression: cron(0 17 * * ? *)\n     Target ID:\n     Task definition family: acm-infra-payment-batch-prod/acm-infra-ecrobo-batch-prod\n     Task definition revision: latest\n     VPC: acm-prod-vpc\n     subnet: acm-prod-public-1a, acm-prod-public-1c\n     Security group: Use an existing security group\n     Security group name: acm-infra-prod-sg\n     Public IP: turned on\n     Container overrides Command override: copy command\n     (<./payment,process_user_blacklist or ./ecrobo,stop_rental>)\n     Environment variable overrides: key (ENV) value (production)\n     ```"
  },
  {
    "category": "Mall",
    "name": "occasion-dress-backend",
    "repo": "occasion-dress-backend",
    "bodyJa": "",
    "bodyEn": "## occasion-dress-backend release\n**Merge PR **\n\n - [ ] https://github.com/air-closet/occasion-dress-backend/pull/xxxx\n\nRelease\n\n - [ ] Run migration rds if needed: npm run migration:run:prod\n - [ ] Run migration docdb if needed: npm run documentdb:migration:run:prod\n - [ ] Deploy: npm run deploy:prod\n\nConfirm release\n\n - [ ] Check ECS > Cluster > service_name > Released service task definition > JSON\n - [ ] Check SHA",
    "bodyVi": ""
  },
  {
    "category": "Mall",
    "name": "phoenix-item",
    "repo": "phoenix-item",
    "bodyJa": "",
    "bodyEn": "## phoenix-item release\n**Merge PR **\n\n - [ ] https://github.com/air-closet/phoenix-item/pull/xxxx\n\nRelease\n\n - [ ] Run migration rds if needed: npm run migration:run:prod\n - [ ] Run migration docdb if needed: npm run documentdb:migration:run:prod\n - [ ] Deploy: npm run deploy:prod\n\nConfirm release\n\n - [ ] Check ECS > Cluster > phoenix-item > Released service task definition > JSON\n - [ ] Check SHA",
    "bodyVi": ""
  },
  {
    "category": "Mall",
    "name": "phoenix-order",
    "repo": "phoenix-order",
    "bodyJa": "",
    "bodyEn": "## phoenix-order release\n**Merge PR **\n\n - [ ] https://github.com/air-closet/phoenix-order/pull/xxxx\n\nRelease\n\n - [ ] Run migration rds if needed: npm run migration:run:prod\n - [ ] Run migration docdb if needed: npm run documentdb:migration:run:prod\n - [ ] Deploy: npm run deploy:prod\n\nConfirm release\n\n - [ ] Check ECS > Cluster > phoenix-order > Released service task definition > JSON\n - [ ] Check SHA",
    "bodyVi": ""
  },
  {
    "category": "Mall",
    "name": "payment",
    "repo": "payment",
    "bodyJa": "",
    "bodyEn": "## phoenix-payment release\n**Merge PR **\n\n - [ ] https://github.com/air-closet/payment/pull/xxxx\n\nRelease\n\n - [ ] Run migration rds if needed: npm run migration:run:prod\n - [ ] Run migration docdb if needed: npm run documentdb:migration:run:prod\n - [ ] Deploy: npm run deploy:prod\n\nConfirm release\n\n - [ ] Check ECS > Cluster > payment > Released service task definition > JSON\n - [ ] Check SHA",
    "bodyVi": ""
  },
  {
    "category": "Men's",
    "name": "Release air-closet-mens",
    "repo": "air-closet-mens",
    "bodyJa": "## air-closet-mens をリリースする\n\n#### 手順\n\n1. **以下の PR をマージする**\n\n   - [ ] air-closet-mens\n         https://github.com/air-closet/air-closet-mens/pull/xxxx\n         ※ PR リンクは必ず変更する\n\n2. **リリースする**\n\n   - [ ] フロントエンドのみの変更の場合\n         `main` ブランチへのマージで自動的にリリースされる\n   - [ ] api または event の変更を含む場合\n         以下の GitHub Actions を実行する\n         https://github.com/air-closet/air-closet-mens/actions/workflows/deploy-production.yml\n         - Branch: `main` を選択\n         - Deploy target: `api` / `event` / `both` から該当するものを選択",
    "bodyEn": "## air-closet-mens release\n\n#### Steps\n\n1. **Merge the following PR**\n\n   - [ ] air-closet-mens\n         https://github.com/air-closet/air-closet-mens/pull/xxxx\n         Update the PR link as needed\n\n2. **Release**\n\n   - [ ] If the PR contains only frontend changes\n         Merging to the `main` branch will automatically release\n   - [ ] If the PR includes api or event changes\n         Execute the following GitHub Actions workflow\n         https://github.com/air-closet/air-closet-mens/actions/workflows/deploy-production.yml\n         - Branch: select `main`\n         - Deploy target: select `api`, `event`, or `both` as needed",
    "bodyVi": "## air-closet-mens release\n\n#### Các bước\n\n1. **Merge PR bên dưới**\n\n   - [ ] air-closet-mens\n         https://github.com/air-closet/air-closet-mens/pull/xxxx\n         Cần thay đổi link PR cho đúng\n\n2. **Release**\n\n   - [ ] Nếu PR chỉ chứa thay đổi frontend\n         Merge vào branch `main` sẽ tự động release\n   - [ ] Nếu PR có thay đổi api hoặc event\n         Chạy GitHub Actions workflow bên dưới\n         https://github.com/air-closet/air-closet-mens/actions/workflows/deploy-production.yml\n         - Branch: chọn `main`\n         - Deploy target: chọn `api`, `event`, hoặc `both` tùy theo thay đổi"
  }
];

async function seed() {
  const inserted = await db
    .insert(releaseTemplates)
    .values(templates)
    .onConflictDoNothing({ target: releaseTemplates.name })
    .returning({ id: releaseTemplates.id });
  console.log(`Seed complete. Inserted ${inserted.length} template(s).`);
}

seed()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => process.exit());
